import { Domine, Albert_Sans } from "next/font/google";
import "./globals.css";

export const domine = Domine({
  variable: "--font-domine",
  subsets: ["latin"],
});

export const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${domine.variable} ${albertSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col content-center w-full flex-wrap">{children}</body>
    </html>
  );
}
